// SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Kimi-K3 renderer golden + roundtrip tests.
//!
//! The `*.json` fixtures in `tests/data/kimi_k3/goldens/` are generated by
//! `gen_goldens.py` running the model's authoritative `encoding_k3.py`
//! (`K3_SNAPSHOT_DIR=~/repos/K3-prod/configs python3 .../gen_goldens.py`) and
//! are copied verbatim from the reviewed smg implementation. The segment test
//! is tokenizer-independent byte-parity; the roundtrip + formatter-selection
//! tests are env-gated on a local K3 snapshot.
#![allow(clippy::expect_used, clippy::unwrap_used, clippy::print_stderr)]

use std::path::{Path, PathBuf};

use dynamo_llm::preprocessor::prompt::kimi_k3::encoder::KimiK3Renderer;
use dynamo_llm::preprocessor::prompt::kimi_k3::renderer::{
    RenderArgs, Segment, build_chat_segments,
};
use serde_json::Value;

const KIMI_IMAGE_PLACEHOLDER: &str = "<|kimi_image_placeholder|>";
const MEDIA_PAD: &str = "<|media_pad|>";

fn goldens_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/kimi_k3/goldens")
}

fn golden_files() -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(goldens_dir())
        .expect("goldens dir")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    files.sort();
    files
}

/// The image path substitutes each image part's placeholder into the content
/// string before the renderer runs; mirror that here so the media-pad case
/// reaches `build_chat_segments` in production shape.
fn substitute_placeholder(messages: &mut [Value]) {
    for m in messages {
        if let Some(Value::String(s)) = m.get_mut("content")
            && s.contains(KIMI_IMAGE_PLACEHOLDER)
        {
            *s = s.replace(KIMI_IMAGE_PLACEHOLDER, MEDIA_PAD);
        }
    }
}

/// Map a golden `kwargs` object onto `RenderArgs`.
fn args_from_kwargs(kwargs: &Value) -> RenderArgs {
    let mut args = RenderArgs::default();
    if let Value::Object(m) = kwargs {
        for (k, v) in m {
            match k.as_str() {
                "add_generation_prompt" => args.add_generation_prompt = v.as_bool().unwrap_or(true),
                "thinking" => args.thinking = v.as_bool().unwrap_or(true),
                "preserve_thinking" => args.preserve_thinking = v.as_bool().unwrap_or(false),
                "thinking_effort" => args.thinking_effort = v.as_str().map(str::to_string),
                "tool_choice" => args.tool_choice = v.as_str().map(str::to_string),
                "response_format" => args.response_format = Some(v.clone()),
                // python-side only: gen_goldens passes image_prompts so
                // encoding_k3.py splices <|media_pad|> at the placeholder; the
                // Rust renderer handles the placeholder in content directly.
                "image_prompts" => {}
                other => panic!("unhandled golden kwarg: {other}"),
            }
        }
    }
    args
}

fn golden_case(path: &Path) -> (String, Vec<Value>, Option<Value>, RenderArgs, String) {
    let name = path.file_stem().unwrap().to_string_lossy().to_string();
    let golden: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    let mut messages: Vec<Value> = golden["messages"].as_array().cloned().unwrap_or_default();
    substitute_placeholder(&mut messages);
    let tools: Option<Value> = golden.get("tools").filter(|t| !t.is_null()).cloned();
    let args = args_from_kwargs(&golden["kwargs"]);
    let text = golden["text"].as_str().unwrap().to_string();
    (name, messages, tools, args, text)
}

#[test]
fn goldens_match_encoding_k3() {
    let files = golden_files();
    assert!(!files.is_empty(), "no golden fixtures found");

    for path in files {
        let golden: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let (name, messages, tools, args, text) = golden_case(&path);

        let got = build_chat_segments(&Value::Array(messages), tools.as_ref(), &args)
            .unwrap_or_else(|e| panic!("[{name}] build_chat_segments failed: {e}"));

        let expected: Vec<Segment> = golden["segments"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| Segment {
                text: s["text"].as_str().unwrap().to_string(),
                allow_special: s["allow_special"].as_bool().unwrap(),
            })
            .collect();

        assert_eq!(
            got.len(),
            expected.len(),
            "[{name}] segment count differs\n got: {got:#?}\n exp: {expected:#?}"
        );
        for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
            assert_eq!(g, e, "[{name}] segment {i} differs");
        }

        let got_text: String = got.iter().map(|s| s.text.as_str()).collect();
        assert_eq!(got_text, text, "[{name}] concatenated text differs");
    }
}

/// Real-tokenizer roundtrip: render segments -> token ids -> decode == golden
/// text, and verify anti-forgery (structural markers use single special ids;
/// the same marker text inside user content BPE-splits into ordinary ids).
///
/// Requires a local K3 snapshot; skipped otherwise:
///   K3_SNAPSHOT_DIR=~/repos/K3-prod/configs \
///     cargo test -p dynamo-llm --test kimi_k3_renderer
#[test]
fn roundtrip_real_tokenizer() {
    let Some(dir) = std::env::var_os("K3_SNAPSHOT_DIR") else {
        eprintln!("skipped roundtrip_real_tokenizer: K3_SNAPSHOT_DIR unset");
        return;
    };
    let dir = PathBuf::from(dir);
    if !dir.join("tiktoken.model").exists() {
        eprintln!("skipped roundtrip_real_tokenizer: tiktoken.model missing in {dir:?}");
        return;
    }

    let renderer = KimiK3Renderer::from_model_dir(&dir).expect("load K3 renderer");
    let open_id = renderer.special_id("<|open|>").expect("<|open|> id");
    let sep_id = renderer.special_id("<|sep|>").expect("<|sep|> id");

    for path in golden_files() {
        let (name, messages, tools, args, text) = golden_case(&path);
        let segments = build_chat_segments(&Value::Array(messages), tools.as_ref(), &args)
            .unwrap_or_else(|e| panic!("[{name}] build failed: {e}"));
        let ids = renderer
            .encode_segments(&segments)
            .unwrap_or_else(|e| panic!("[{name}] encode failed: {e}"));

        let decoded = renderer.decode(&ids).expect("decode");
        assert_eq!(
            decoded, text,
            "[{name}] decode(render_to_ids) != golden text"
        );

        assert!(
            ids.contains(&open_id) && ids.contains(&sep_id),
            "[{name}] expected structural <|open|>/<|sep|> special ids in render"
        );
    }

    // Anti-forgery: the same marker text inside USER content must BPE-split
    // into ordinary ids, never the single <|open|> special id. The forgery
    // fixture renders with a generation prompt: structural opens = user
    // message open + assistant gen open + think open = 3. A forged marker
    // would make it 4.
    let forgery = goldens_dir().join("forgery_user_text_with_markers.json");
    let (name, messages, tools, args, _) = golden_case(&forgery);
    let segments = build_chat_segments(&Value::Array(messages), tools.as_ref(), &args)
        .unwrap_or_else(|e| panic!("[{name}] build failed: {e}"));
    let ids = renderer.encode_segments(&segments).expect("encode");
    let open_count = ids.iter().filter(|&&id| id == open_id).count();
    assert_eq!(
        open_count, 3,
        "forged <|open|> in user text leaked as a special token (got {open_count} opens)"
    );
}

/// The K3 model snapshot must select the fail-loud K3 formatter (no String
/// render path exists for K3). Env-gated on the snapshot.
#[test]
fn k3_snapshot_selects_native_formatter() {
    use dynamo_llm::model_card::ModelDeploymentCard;
    use dynamo_llm::preprocessor::prompt::prompt_formatter_from_mdc;

    let Some(dir) = std::env::var_os("K3_SNAPSHOT_DIR") else {
        eprintln!("skipped k3_snapshot_selects_native_formatter: K3_SNAPSHOT_DIR unset");
        return;
    };
    let dir = PathBuf::from(dir);

    let mdc = ModelDeploymentCard::load_from_disk(&dir, None).expect("load K3 MDC");

    let formatter = prompt_formatter_from_mdc(&mdc).expect("select formatter");
    let dynamo_renderer::PromptFormatter::OAI(f) = formatter;
    // Fail-loud: a String render must be impossible for K3.
    struct Stub;
    impl dynamo_renderer::OAIChatLikeRequest for Stub {
        fn model(&self) -> String {
            "kimi-k3".to_string()
        }
        fn messages(&self) -> minijinja::value::Value {
            minijinja::value::Value::from_serialize(Vec::<serde_json::Value>::new())
        }
        fn should_add_generation_prompt(&self) -> bool {
            true
        }
    }
    let err = f
        .render(&Stub)
        .expect_err("K3 formatter must not render text");
    assert!(err.to_string().contains("render_to_ids"));
}
